from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from accounts.spotify import get_user_playlists, get_playlist_tracks, get_track_info
import requests
import requests
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
import json
from .models import KeptSong
from django.views.decorators.http import require_POST
from django.contrib.auth import get_user_model
from django.shortcuts import get_object_or_404


@login_required
def playlist_dashboard(request):
    """Fetch the user's playlists from Spotify and render them."""
    try:
        data = get_user_playlists(request.user)
        playlists = data.get("items", [])
    except requests.RequestException as e:
        playlists = []
        error_message = f"Failed to fetch playlists: {e}"
        return render(
            request,
            "playlists/dashboard.html",
            {"error_message": error_message, "playlists": playlists},
        )
    return render(request, "playlists/dashboard.html", {"playlists": playlists})


@login_required
def render_edit(request, playlist_id=None):
    """Render the edit UI for a specific playlist.

    If playlist_id is provided we load that playlist; otherwise fall back to the user's
    first playlist (legacy behaviour).
    """
    data = get_user_playlists(request.user)
    playlists = data.get("items", [])

    # find requested playlist by id if given
    playlist = None
    if playlist_id:
        for p in playlists:
            if str(p.get("id")) == str(playlist_id):
                playlist = p
                break

    # default to first playlist
    if not playlist:
        if playlists:
            playlist = playlists[0]
        else:
            return render(request, "playlists/edit.html", {"songs": [], "playlist_name": "", "playlist_id": ""})

    songs = get_playlist_tracks_with_previews(request.user, playlist["id"])

    # Exclude only tracks the user explicitly removed (kept==False).
    # Kept songs should remain in the edit stack so users can re-edit them.
    try:
        removed_uris = set(
            KeptSong.objects.filter(user=request.user, playlist_id=playlist["id"], kept=False)
            .values_list("track_uri", flat=True)
        )
    except Exception:
        removed_uris = set()

    filtered_songs = [s for s in songs if s.get("track_uri") not in removed_uris]

    # send playlist id and name to the template
    return render(
        request,
        "playlists/edit.html",
        {"songs": filtered_songs, "playlist_name": playlist.get("name", ""), "playlist_id": playlist["id"]},
    )


@login_required
@csrf_exempt
@require_POST
def save_decision(request):
    """API endpoint to save a user's keep/remove decision for a track in a playlist.

    Expects JSON body with: playlist_id, track_uri, name, artists (list), image_url, preview_url, spotify_url, kept (bool)
    """
    try:
        payload = json.loads(request.body)
    except json.JSONDecodeError:
        return JsonResponse({"error": "invalid_json"}, status=400)

    user = request.user
    playlist_id = payload.get("playlist_id")
    track_uri = payload.get("track_uri")
    name = payload.get("name")
    artists = payload.get("artists")
    image_url = payload.get("image_url")
    preview_url = payload.get("preview_url")
    spotify_url = payload.get("spotify_url")
    kept = payload.get("kept")

    if not all([playlist_id, track_uri]) or kept is None:
        return JsonResponse({"error": "missing_fields"}, status=400)

    # Upsert the decision
    obj, created = KeptSong.objects.update_or_create(
        user=user, playlist_id=playlist_id, track_uri=track_uri,
        defaults={
            "name": name or "",
            "artists": artists or [],
            "image_url": image_url,
            "preview_url": preview_url,
            "spotify_url": spotify_url,
            "kept": bool(kept),
        },
    )

    return JsonResponse({"status": "saved", "created": created})


@login_required
def kept_view(request, playlist_id):
    """Render a page showing kept and removed songs for given playlist id."""
    # Query the KeptSong objects for this user+playlist
    qs = KeptSong.objects.filter(user=request.user, playlist_id=playlist_id).order_by('-created_at')
    kept = [
        {
            "name": s.name,
            "artists": s.artists or [],
            "image_url": s.image_url,
            "preview_url": s.preview_url,
            "spotify_url": s.spotify_url,
            "track_uri": s.track_uri,
        }
        for s in qs.filter(kept=True)
    ]

    removed = [
        {
            "name": s.name,
            "artists": s.artists or [],
            "image_url": s.image_url,
            "preview_url": s.preview_url,
            "spotify_url": s.spotify_url,
            "track_uri": s.track_uri,
        }
        for s in qs.filter(kept=False)
    ]

    return render(request, "playlists/kept.html", {"kept": kept, "removed": removed, "playlist_id": playlist_id})


@login_required
@require_POST
def reconsider_decision(request):
    """Reconsider a previously saved decision: remove the KeptSong entry so the track
    returns to the unedited pool.

    Expects JSON body with: playlist_id, track_uri
    """
    try:
        payload = json.loads(request.body)
    except json.JSONDecodeError:
        return JsonResponse({"error": "invalid_json"}, status=400)

    playlist_id = payload.get("playlist_id")
    track_uri = payload.get("track_uri")

    if not playlist_id or not track_uri:
        return JsonResponse({"error": "missing_fields"}, status=400)

    # Delete any existing decision for this user/playlist/track
    deleted, _ = KeptSong.objects.filter(user=request.user, playlist_id=playlist_id, track_uri=track_uri).delete()

    return JsonResponse({"status": "deleted", "deleted": deleted})


def get_playlist_tracks_with_previews(user, playlist_id):
    raw_tracks = get_playlist_tracks(user, playlist_id)
    tracks_with_preview = []

    for item in raw_tracks:
        track = item["track"]
        track_id = track["id"]
        track_info = get_track_info(user, track_id)
        tracks_with_preview.append(
            {
                "name": track_info["name"],
                "image_url": (
                    track_info["album"]["images"][0]["url"]
                    if track_info["album"]["images"]
                    else None
                ),
                "preview_url": track_info.get("preview_url"),
                "spotify_url": track_info["external_urls"]["spotify"],
                "artists": [artist["name"] for artist in track_info["artists"]],
                "track_uri": track_info.get("uri"),
            }
        )

    return tracks_with_preview


[
    {
        "added_at": "2025-11-04T19:13:45Z",
        "added_by": {
            "external_urls": {
                "spotify": "https://open.spotify.com/user/31bruxgr2pyas6a72hpa7oeyjkwu"
            },
            "href": "https://api.spotify.com/v1/users/31bruxgr2pyas6a72hpa7oeyjkwu",
            "id": "31bruxgr2pyas6a72hpa7oeyjkwu",
            "type": "user",
            "uri": "spotify:user:31bruxgr2pyas6a72hpa7oeyjkwu",
        },
        "is_local": False,
        "primary_color": None,
        "track": {
            "preview_url": None,
            "available_markets": [
                "AR",
                "AU",
                "AT",
                "BE",
                "BO",
                "BR",
                "BG",
                "CA",
                "CL",
                "CO",
                "CR",
                "CY",
                "CZ",
                "DK",
                "DO",
                "DE",
                "EC",
                "EE",
                "SV",
                "FI",
                "FR",
                "GR",
                "GT",
                "HN",
                "HK",
                "HU",
                "IS",
                "IE",
                "IT",
                "LV",
                "LT",
                "LU",
                "MY",
                "MT",
                "MX",
                "NL",
                "NZ",
                "NI",
                "NO",
                "PA",
                "PY",
                "PE",
                "PH",
                "PL",
                "PT",
                "SG",
                "SK",
                "ES",
                "SE",
                "CH",
                "TW",
                "TR",
                "UY",
                "US",
                "GB",
                "AD",
                "LI",
                "MC",
                "ID",
                "JP",
                "TH",
                "VN",
                "RO",
                "IL",
                "ZA",
                "SA",
                "AE",
                "BH",
                "QA",
                "OM",
                "KW",
                "EG",
                "MA",
                "DZ",
                "TN",
                "LB",
                "JO",
                "PS",
                "IN",
                "BY",
                "KZ",
                "MD",
                "UA",
                "AL",
                "BA",
                "HR",
                "ME",
                "MK",
                "RS",
                "SI",
                "KR",
                "BD",
                "PK",
                "LK",
                "GH",
                "KE",
                "NG",
                "TZ",
                "UG",
                "AG",
                "AM",
                "BS",
                "BB",
                "BZ",
                "BT",
                "BW",
                "BF",
                "CV",
                "CW",
                "DM",
                "FJ",
                "GM",
                "GE",
                "GD",
                "GW",
                "GY",
                "HT",
                "JM",
                "KI",
                "LS",
                "LR",
                "MW",
                "MV",
                "ML",
                "MH",
                "FM",
                "NA",
                "NR",
                "NE",
                "PW",
                "PG",
                "PR",
                "WS",
                "SM",
                "ST",
                "SN",
                "SC",
                "SL",
                "SB",
                "KN",
                "LC",
                "VC",
                "SR",
                "TL",
                "TO",
                "TT",
                "TV",
                "VU",
                "AZ",
                "BN",
                "BI",
                "KH",
                "CM",
                "TD",
                "KM",
                "GQ",
                "SZ",
                "GA",
                "GN",
                "KG",
                "LA",
                "MO",
                "MR",
                "MN",
                "NP",
                "RW",
                "TG",
                "UZ",
                "ZW",
                "BJ",
                "MG",
                "MU",
                "MZ",
                "AO",
                "CI",
                "DJ",
                "ZM",
                "CD",
                "CG",
                "IQ",
                "LY",
                "TJ",
                "VE",
                "ET",
                "XK",
            ],
            "explicit": False,
            "type": "track",
            "episode": False,
            "track": True,
            "album": {
                "available_markets": [
                    "AR",
                    "AU",
                    "AT",
                    "BE",
                    "BO",
                    "BR",
                    "BG",
                    "CA",
                    "CL",
                    "CO",
                    "CR",
                    "CY",
                    "CZ",
                    "DK",
                    "DO",
                    "DE",
                    "EC",
                    "EE",
                    "SV",
                    "FI",
                    "FR",
                    "GR",
                    "GT",
                    "HN",
                    "HK",
                    "HU",
                    "IS",
                    "IE",
                    "IT",
                    "LV",
                    "LT",
                    "LU",
                    "MY",
                    "MT",
                    "MX",
                    "NL",
                    "NZ",
                    "NI",
                    "NO",
                    "PA",
                    "PY",
                    "PE",
                    "PH",
                    "PL",
                    "PT",
                    "SG",
                    "SK",
                    "ES",
                    "SE",
                    "CH",
                    "TW",
                    "TR",
                    "UY",
                    "US",
                    "GB",
                    "AD",
                    "LI",
                    "MC",
                    "ID",
                    "JP",
                    "TH",
                    "VN",
                    "RO",
                    "IL",
                    "ZA",
                    "SA",
                    "AE",
                    "BH",
                    "QA",
                    "OM",
                    "KW",
                    "EG",
                    "MA",
                    "DZ",
                    "TN",
                    "LB",
                    "JO",
                    "PS",
                    "IN",
                    "BY",
                    "KZ",
                    "MD",
                    "UA",
                    "AL",
                    "BA",
                    "HR",
                    "ME",
                    "MK",
                    "RS",
                    "SI",
                    "KR",
                    "BD",
                    "PK",
                    "LK",
                    "GH",
                    "KE",
                    "NG",
                    "TZ",
                    "UG",
                    "AG",
                    "AM",
                    "BS",
                    "BB",
                    "BZ",
                    "BT",
                    "BW",
                    "BF",
                    "CV",
                    "CW",
                    "DM",
                    "FJ",
                    "GM",
                    "GE",
                    "GD",
                    "GW",
                    "GY",
                    "HT",
                    "JM",
                    "KI",
                    "LS",
                    "LR",
                    "MW",
                    "MV",
                    "ML",
                    "MH",
                    "FM",
                    "NA",
                    "NR",
                    "NE",
                    "PW",
                    "PG",
                    "PR",
                    "WS",
                    "SM",
                    "ST",
                    "SN",
                    "SC",
                    "SL",
                    "SB",
                    "KN",
                    "LC",
                    "VC",
                    "SR",
                    "TL",
                    "TO",
                    "TT",
                    "TV",
                    "VU",
                    "AZ",
                    "BN",
                    "BI",
                    "KH",
                    "CM",
                    "TD",
                    "KM",
                    "GQ",
                    "SZ",
                    "GA",
                    "GN",
                    "KG",
                    "LA",
                    "MO",
                    "MR",
                    "MN",
                    "NP",
                    "RW",
                    "TG",
                    "UZ",
                    "ZW",
                    "BJ",
                    "MG",
                    "MU",
                    "MZ",
                    "AO",
                    "CI",
                    "DJ",
                    "ZM",
                    "CD",
                    "CG",
                    "IQ",
                    "LY",
                    "TJ",
                    "VE",
                    "ET",
                    "XK",
                ],
                "type": "album",
                "album_type": "album",
                "href": "https://api.spotify.com/v1/albums/3XH1loQu2ohrMnmGCJMPYa",
                "id": "3XH1loQu2ohrMnmGCJMPYa",
                "images": [
                    {
                        "height": 640,
                        "url": "https://i.scdn.co/image/ab67616d0000b273f17110b67858552d3f18e1e0",
                        "width": 640,
                    },
                    {
                        "height": 300,
                        "url": "https://i.scdn.co/image/ab67616d00001e02f17110b67858552d3f18e1e0",
                        "width": 300,
                    },
                    {
                        "height": 64,
                        "url": "https://i.scdn.co/image/ab67616d00004851f17110b67858552d3f18e1e0",
                        "width": 64,
                    },
                ],
                "name": "Duotones",
                "release_date": "1986-09-01",
                "release_date_precision": "day",
                "uri": "spotify:album:3XH1loQu2ohrMnmGCJMPYa",
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/6I3M904Y9IwgDjrQ9pANiB"
                        },
                        "href": "https://api.spotify.com/v1/artists/6I3M904Y9IwgDjrQ9pANiB",
                        "id": "6I3M904Y9IwgDjrQ9pANiB",
                        "name": "Kenny G",
                        "type": "artist",
                        "uri": "spotify:artist:6I3M904Y9IwgDjrQ9pANiB",
                    }
                ],
                "external_urls": {
                    "spotify": "https://open.spotify.com/album/3XH1loQu2ohrMnmGCJMPYa"
                },
                "total_tracks": 10,
            },
            "artists": [
                {
                    "external_urls": {
                        "spotify": "https://open.spotify.com/artist/6I3M904Y9IwgDjrQ9pANiB"
                    },
                    "href": "https://api.spotify.com/v1/artists/6I3M904Y9IwgDjrQ9pANiB",
                    "id": "6I3M904Y9IwgDjrQ9pANiB",
                    "name": "Kenny G",
                    "type": "artist",
                    "uri": "spotify:artist:6I3M904Y9IwgDjrQ9pANiB",
                }
            ],
            "disc_number": 1,
            "track_number": 1,
            "duration_ms": 303333,
            "external_ids": {"isrc": "USAR18600113"},
            "external_urls": {
                "spotify": "https://open.spotify.com/track/3Yx4nbYHdmHQdnYAukyHJR"
            },
            "href": "https://api.spotify.com/v1/tracks/3Yx4nbYHdmHQdnYAukyHJR",
            "id": "3Yx4nbYHdmHQdnYAukyHJR",
            "name": "Songbird",
            "popularity": 49,
            "uri": "spotify:track:3Yx4nbYHdmHQdnYAukyHJR",
            "is_local": False,
        },
        "video_thumbnail": {"url": None},
    },
    {
        "added_at": "2025-11-04T19:13:46Z",
        "added_by": {
            "external_urls": {
                "spotify": "https://open.spotify.com/user/31bruxgr2pyas6a72hpa7oeyjkwu"
            },
            "href": "https://api.spotify.com/v1/users/31bruxgr2pyas6a72hpa7oeyjkwu",
            "id": "31bruxgr2pyas6a72hpa7oeyjkwu",
            "type": "user",
            "uri": "spotify:user:31bruxgr2pyas6a72hpa7oeyjkwu",
        },
        "is_local": False,
        "primary_color": None,
        "track": {
            "preview_url": None,
            "available_markets": [
                "AR",
                "AU",
                "AT",
                "BE",
                "BO",
                "BR",
                "BG",
                "CA",
                "CL",
                "CO",
                "CR",
                "CY",
                "CZ",
                "DK",
                "DO",
                "DE",
                "EC",
                "EE",
                "SV",
                "FI",
                "FR",
                "GR",
                "GT",
                "HN",
                "HK",
                "HU",
                "IS",
                "IE",
                "IT",
                "LV",
                "LT",
                "LU",
                "MY",
                "MT",
                "MX",
                "NL",
                "NZ",
                "NI",
                "NO",
                "PA",
                "PY",
                "PE",
                "PH",
                "PL",
                "PT",
                "SG",
                "SK",
                "ES",
                "SE",
                "CH",
                "TW",
                "TR",
                "UY",
                "US",
                "GB",
                "AD",
                "LI",
                "MC",
                "ID",
                "JP",
                "TH",
                "VN",
                "RO",
                "IL",
                "ZA",
                "SA",
                "AE",
                "BH",
                "QA",
                "OM",
                "KW",
                "EG",
                "MA",
                "DZ",
                "TN",
                "LB",
                "JO",
                "PS",
                "IN",
                "KZ",
                "MD",
                "UA",
                "AL",
                "BA",
                "HR",
                "ME",
                "MK",
                "RS",
                "SI",
                "KR",
                "BD",
                "PK",
                "LK",
                "GH",
                "KE",
                "NG",
                "TZ",
                "UG",
                "AG",
                "AM",
                "BS",
                "BB",
                "BZ",
                "BT",
                "BW",
                "BF",
                "CV",
                "CW",
                "DM",
                "FJ",
                "GM",
                "GE",
                "GD",
                "GW",
                "GY",
                "HT",
                "JM",
                "KI",
                "LS",
                "LR",
                "MW",
                "MV",
                "ML",
                "MH",
                "FM",
                "NA",
                "NR",
                "NE",
                "PW",
                "PG",
                "WS",
                "SM",
                "ST",
                "SN",
                "SC",
                "SL",
                "SB",
                "KN",
                "LC",
                "VC",
                "SR",
                "TL",
                "TO",
                "TT",
                "TV",
                "VU",
                "AZ",
                "BN",
                "BI",
                "KH",
                "CM",
                "TD",
                "KM",
                "GQ",
                "SZ",
                "GA",
                "GN",
                "KG",
                "LA",
                "MO",
                "MR",
                "MN",
                "NP",
                "RW",
                "TG",
                "UZ",
                "ZW",
                "BJ",
                "MG",
                "MU",
                "MZ",
                "AO",
                "CI",
                "DJ",
                "ZM",
                "CD",
                "CG",
                "IQ",
                "LY",
                "TJ",
                "VE",
                "ET",
                "XK",
            ],
            "explicit": False,
            "type": "track",
            "episode": False,
            "track": True,
            "album": {
                "available_markets": [
                    "AR",
                    "AU",
                    "AT",
                    "BE",
                    "BO",
                    "BR",
                    "BG",
                    "CA",
                    "CL",
                    "CO",
                    "CR",
                    "CY",
                    "CZ",
                    "DK",
                    "DO",
                    "DE",
                    "EC",
                    "EE",
                    "SV",
                    "FI",
                    "FR",
                    "GR",
                    "GT",
                    "HN",
                    "HK",
                    "HU",
                    "IS",
                    "IE",
                    "IT",
                    "LV",
                    "LT",
                    "LU",
                    "MY",
                    "MT",
                    "MX",
                    "NL",
                    "NZ",
                    "NI",
                    "NO",
                    "PA",
                    "PY",
                    "PE",
                    "PH",
                    "PL",
                    "PT",
                    "SG",
                    "SK",
                    "ES",
                    "SE",
                    "CH",
                    "TW",
                    "TR",
                    "UY",
                    "US",
                    "GB",
                    "AD",
                    "LI",
                    "MC",
                    "ID",
                    "JP",
                    "TH",
                    "VN",
                    "RO",
                    "IL",
                    "ZA",
                    "SA",
                    "AE",
                    "BH",
                    "QA",
                    "OM",
                    "KW",
                    "EG",
                    "MA",
                    "DZ",
                    "TN",
                    "LB",
                    "JO",
                    "PS",
                    "IN",
                    "KZ",
                    "MD",
                    "UA",
                    "AL",
                    "BA",
                    "HR",
                    "ME",
                    "MK",
                    "RS",
                    "SI",
                    "KR",
                    "BD",
                    "PK",
                    "LK",
                    "GH",
                    "KE",
                    "NG",
                    "TZ",
                    "UG",
                    "AG",
                    "AM",
                    "BS",
                    "BB",
                    "BZ",
                    "BT",
                    "BW",
                    "BF",
                    "CV",
                    "CW",
                    "DM",
                    "FJ",
                    "GM",
                    "GE",
                    "GD",
                    "GW",
                    "GY",
                    "HT",
                    "JM",
                    "KI",
                    "LS",
                    "LR",
                    "MW",
                    "MV",
                    "ML",
                    "MH",
                    "FM",
                    "NA",
                    "NR",
                    "NE",
                    "PW",
                    "PG",
                    "WS",
                    "SM",
                    "ST",
                    "SN",
                    "SC",
                    "SL",
                    "SB",
                    "KN",
                    "LC",
                    "VC",
                    "SR",
                    "TL",
                    "TO",
                    "TT",
                    "TV",
                    "VU",
                    "AZ",
                    "BN",
                    "BI",
                    "KH",
                    "CM",
                    "TD",
                    "KM",
                    "GQ",
                    "SZ",
                    "GA",
                    "GN",
                    "KG",
                    "LA",
                    "MO",
                    "MR",
                    "MN",
                    "NP",
                    "RW",
                    "TG",
                    "UZ",
                    "ZW",
                    "BJ",
                    "MG",
                    "MU",
                    "MZ",
                    "AO",
                    "CI",
                    "DJ",
                    "ZM",
                    "CD",
                    "CG",
                    "IQ",
                    "LY",
                    "TJ",
                    "VE",
                    "ET",
                    "XK",
                ],
                "type": "album",
                "album_type": "single",
                "href": "https://api.spotify.com/v1/albums/68CN2LzY8MoxO2udy2C22e",
                "id": "68CN2LzY8MoxO2udy2C22e",
                "images": [
                    {
                        "height": 640,
                        "url": "https://i.scdn.co/image/ab67616d0000b273e6065f209e0a01986206bd53",
                        "width": 640,
                    },
                    {
                        "height": 300,
                        "url": "https://i.scdn.co/image/ab67616d00001e02e6065f209e0a01986206bd53",
                        "width": 300,
                    },
                    {
                        "height": 64,
                        "url": "https://i.scdn.co/image/ab67616d00004851e6065f209e0a01986206bd53",
                        "width": 64,
                    },
                ],
                "name": "Sailor Song",
                "release_date": "2024-07-26",
                "release_date_precision": "day",
                "uri": "spotify:album:68CN2LzY8MoxO2udy2C22e",
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/1iCnM8foFssWlPRLfAbIwo"
                        },
                        "href": "https://api.spotify.com/v1/artists/1iCnM8foFssWlPRLfAbIwo",
                        "id": "1iCnM8foFssWlPRLfAbIwo",
                        "name": "Gigi Perez",
                        "type": "artist",
                        "uri": "spotify:artist:1iCnM8foFssWlPRLfAbIwo",
                    }
                ],
                "external_urls": {
                    "spotify": "https://open.spotify.com/album/68CN2LzY8MoxO2udy2C22e"
                },
                "total_tracks": 1,
            },
            "artists": [
                {
                    "external_urls": {
                        "spotify": "https://open.spotify.com/artist/1iCnM8foFssWlPRLfAbIwo"
                    },
                    "href": "https://api.spotify.com/v1/artists/1iCnM8foFssWlPRLfAbIwo",
                    "id": "1iCnM8foFssWlPRLfAbIwo",
                    "name": "Gigi Perez",
                    "type": "artist",
                    "uri": "spotify:artist:1iCnM8foFssWlPRLfAbIwo",
                }
            ],
            "disc_number": 1,
            "track_number": 1,
            "duration_ms": 211978,
            "external_ids": {"isrc": "USHM92438095"},
            "external_urls": {
                "spotify": "https://open.spotify.com/track/2262bWmqomIaJXwCRHr13j"
            },
            "href": "https://api.spotify.com/v1/tracks/2262bWmqomIaJXwCRHr13j",
            "id": "2262bWmqomIaJXwCRHr13j",
            "name": "Sailor Song",
            "popularity": 87,
            "uri": "spotify:track:2262bWmqomIaJXwCRHr13j",
            "is_local": False,
        },
        "video_thumbnail": {"url": None},
    },
    {
        "added_at": "2025-11-04T19:13:48Z",
        "added_by": {
            "external_urls": {
                "spotify": "https://open.spotify.com/user/31bruxgr2pyas6a72hpa7oeyjkwu"
            },
            "href": "https://api.spotify.com/v1/users/31bruxgr2pyas6a72hpa7oeyjkwu",
            "id": "31bruxgr2pyas6a72hpa7oeyjkwu",
            "type": "user",
            "uri": "spotify:user:31bruxgr2pyas6a72hpa7oeyjkwu",
        },
        "is_local": False,
        "primary_color": None,
        "track": {
            "preview_url": None,
            "available_markets": [
                "AR",
                "AU",
                "AT",
                "BE",
                "BO",
                "BR",
                "BG",
                "CA",
                "CL",
                "CO",
                "CR",
                "CY",
                "CZ",
                "DK",
                "DO",
                "DE",
                "EC",
                "EE",
                "SV",
                "FI",
                "FR",
                "GR",
                "GT",
                "HN",
                "HK",
                "HU",
                "IS",
                "IE",
                "IT",
                "LV",
                "LT",
                "LU",
                "MY",
                "MT",
                "MX",
                "NL",
                "NZ",
                "NI",
                "NO",
                "PA",
                "PY",
                "PE",
                "PH",
                "PL",
                "PT",
                "SG",
                "SK",
                "ES",
                "SE",
                "CH",
                "TW",
                "TR",
                "UY",
                "US",
                "GB",
                "AD",
                "LI",
                "MC",
                "ID",
                "JP",
                "TH",
                "VN",
                "RO",
                "IL",
                "ZA",
                "SA",
                "AE",
                "BH",
                "QA",
                "OM",
                "KW",
                "EG",
                "MA",
                "DZ",
                "TN",
                "LB",
                "JO",
                "PS",
                "IN",
                "KZ",
                "MD",
                "UA",
                "AL",
                "BA",
                "HR",
                "ME",
                "MK",
                "RS",
                "SI",
                "KR",
                "BD",
                "PK",
                "LK",
                "GH",
                "KE",
                "NG",
                "TZ",
                "UG",
                "AG",
                "AM",
                "BS",
                "BB",
                "BZ",
                "BT",
                "BW",
                "BF",
                "CV",
                "CW",
                "DM",
                "FJ",
                "GM",
                "GE",
                "GD",
                "GW",
                "GY",
                "HT",
                "JM",
                "KI",
                "LS",
                "LR",
                "MW",
                "MV",
                "ML",
                "MH",
                "FM",
                "NA",
                "NR",
                "NE",
                "PW",
                "PG",
                "WS",
                "SM",
                "ST",
                "SN",
                "SC",
                "SL",
                "SB",
                "KN",
                "LC",
                "VC",
                "SR",
                "TL",
                "TO",
                "TT",
                "TV",
                "VU",
                "AZ",
                "BN",
                "BI",
                "KH",
                "CM",
                "TD",
                "KM",
                "GQ",
                "SZ",
                "GA",
                "GN",
                "KG",
                "LA",
                "MO",
                "MR",
                "MN",
                "NP",
                "RW",
                "TG",
                "UZ",
                "ZW",
                "BJ",
                "MG",
                "MU",
                "MZ",
                "AO",
                "CI",
                "DJ",
                "ZM",
                "CD",
                "CG",
                "IQ",
                "LY",
                "TJ",
                "VE",
                "ET",
                "XK",
            ],
            "explicit": False,
            "type": "track",
            "episode": False,
            "track": True,
            "album": {
                "available_markets": [
                    "AR",
                    "AU",
                    "AT",
                    "BE",
                    "BO",
                    "BR",
                    "BG",
                    "CA",
                    "CL",
                    "CO",
                    "CR",
                    "CY",
                    "CZ",
                    "DK",
                    "DO",
                    "DE",
                    "EC",
                    "EE",
                    "SV",
                    "FI",
                    "FR",
                    "GR",
                    "GT",
                    "HN",
                    "HK",
                    "HU",
                    "IS",
                    "IE",
                    "IT",
                    "LV",
                    "LT",
                    "LU",
                    "MY",
                    "MT",
                    "MX",
                    "NL",
                    "NZ",
                    "NI",
                    "NO",
                    "PA",
                    "PY",
                    "PE",
                    "PH",
                    "PL",
                    "PT",
                    "SG",
                    "SK",
                    "ES",
                    "SE",
                    "CH",
                    "TW",
                    "TR",
                    "UY",
                    "US",
                    "GB",
                    "AD",
                    "LI",
                    "MC",
                    "ID",
                    "JP",
                    "TH",
                    "VN",
                    "RO",
                    "IL",
                    "ZA",
                    "SA",
                    "AE",
                    "BH",
                    "QA",
                    "OM",
                    "KW",
                    "EG",
                    "MA",
                    "DZ",
                    "TN",
                    "LB",
                    "JO",
                    "PS",
                    "IN",
                    "KZ",
                    "MD",
                    "UA",
                    "AL",
                    "BA",
                    "HR",
                    "ME",
                    "MK",
                    "RS",
                    "SI",
                    "KR",
                    "BD",
                    "PK",
                    "LK",
                    "GH",
                    "KE",
                    "NG",
                    "TZ",
                    "UG",
                    "AG",
                    "AM",
                    "BS",
                    "BB",
                    "BZ",
                    "BT",
                    "BW",
                    "BF",
                    "CV",
                    "CW",
                    "DM",
                    "FJ",
                    "GM",
                    "GE",
                    "GD",
                    "GW",
                    "GY",
                    "HT",
                    "JM",
                    "KI",
                    "LS",
                    "LR",
                    "MW",
                    "MV",
                    "ML",
                    "MH",
                    "FM",
                    "NA",
                    "NR",
                    "NE",
                    "PW",
                    "PG",
                    "WS",
                    "SM",
                    "ST",
                    "SN",
                    "SC",
                    "SL",
                    "SB",
                    "KN",
                    "LC",
                    "VC",
                    "SR",
                    "TL",
                    "TO",
                    "TT",
                    "TV",
                    "VU",
                    "AZ",
                    "BN",
                    "BI",
                    "KH",
                    "CM",
                    "TD",
                    "KM",
                    "GQ",
                    "SZ",
                    "GA",
                    "GN",
                    "KG",
                    "LA",
                    "MO",
                    "MR",
                    "MN",
                    "NP",
                    "RW",
                    "TG",
                    "UZ",
                    "ZW",
                    "BJ",
                    "MG",
                    "MU",
                    "MZ",
                    "AO",
                    "CI",
                    "DJ",
                    "ZM",
                    "CD",
                    "CG",
                    "IQ",
                    "LY",
                    "TJ",
                    "VE",
                    "ET",
                    "XK",
                ],
                "type": "album",
                "album_type": "single",
                "href": "https://api.spotify.com/v1/albums/68CN2LzY8MoxO2udy2C22e",
                "id": "68CN2LzY8MoxO2udy2C22e",
                "images": [
                    {
                        "height": 640,
                        "url": "https://i.scdn.co/image/ab67616d0000b273e6065f209e0a01986206bd53",
                        "width": 640,
                    },
                    {
                        "height": 300,
                        "url": "https://i.scdn.co/image/ab67616d00001e02e6065f209e0a01986206bd53",
                        "width": 300,
                    },
                    {
                        "height": 64,
                        "url": "https://i.scdn.co/image/ab67616d00004851e6065f209e0a01986206bd53",
                        "width": 64,
                    },
                ],
                "name": "Sailor Song",
                "release_date": "2024-07-26",
                "release_date_precision": "day",
                "uri": "spotify:album:68CN2LzY8MoxO2udy2C22e",
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/1iCnM8foFssWlPRLfAbIwo"
                        },
                        "href": "https://api.spotify.com/v1/artists/1iCnM8foFssWlPRLfAbIwo",
                        "id": "1iCnM8foFssWlPRLfAbIwo",
                        "name": "Gigi Perez",
                        "type": "artist",
                        "uri": "spotify:artist:1iCnM8foFssWlPRLfAbIwo",
                    }
                ],
                "external_urls": {
                    "spotify": "https://open.spotify.com/album/68CN2LzY8MoxO2udy2C22e"
                },
                "total_tracks": 1,
            },
            "artists": [
                {
                    "external_urls": {
                        "spotify": "https://open.spotify.com/artist/1iCnM8foFssWlPRLfAbIwo"
                    },
                    "href": "https://api.spotify.com/v1/artists/1iCnM8foFssWlPRLfAbIwo",
                    "id": "1iCnM8foFssWlPRLfAbIwo",
                    "name": "Gigi Perez",
                    "type": "artist",
                    "uri": "spotify:artist:1iCnM8foFssWlPRLfAbIwo",
                }
            ],
            "disc_number": 1,
            "track_number": 1,
            "duration_ms": 211978,
            "external_ids": {"isrc": "USHM92438095"},
            "external_urls": {
                "spotify": "https://open.spotify.com/track/2262bWmqomIaJXwCRHr13j"
            },
            "href": "https://api.spotify.com/v1/tracks/2262bWmqomIaJXwCRHr13j",
            "id": "2262bWmqomIaJXwCRHr13j",
            "name": "Sailor Song",
            "popularity": 87,
            "uri": "spotify:track:2262bWmqomIaJXwCRHr13j",
            "is_local": False,
        },
        "video_thumbnail": {"url": None},
    },
]
